### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by mmcdole**
Just did a run through this on my machine and I kept track of some small fixes.  

I was also going to mention that I think people should mostly use wifi-menu and the guide should delete a lot of the manual wifi network setup instructions, but I see that has already been covered in #8.

### CODE REVIEW

**Comment by ejmg** [comment]
This is awesome, thank you for catching these mistakes. The conf fix in particular is a good catch, I could have caused some real headaches with that one. I am merging them :tada:!

As an aside with the wifi menu discussion, this is how I feel so far:

- netctl is a really good tool
- wifi-menu makes netctl a breeze to use
- however, wifi-menu often can't work on the first try with networks that have more advanced wpa-enterprise security settings in place
- this leaves users with no wifi and a config file they need to fix themselves
- consequently, knowing (somewhat) how netctl works internally is important in these cases as the fixes are often trivial, but common enough in occurrence (at least in my experience)

That said, if you want to make a section that advises how to use wifi-menu initially and then points the reader to the netctl stuff in case it does not work, then I welcome the change.

**Comment by mmcdole** [comment]
That actually makes a lot of a sense about knowing how to manually configure for those special cases.

I'm also considering submitting something on Intel graphics configuration.  I'm curious, have you done any config for your Intel drivers?

I've created a `/etc/X11/` config with the following contents based on responses from other X1C6 owners:

```
  Section "Device"
        Identifier  "Intel Graphics"
        Driver "intel"
        Option "AccelMethod" "sna"
        Option "TearFree" "true"
        Option "DRI" "3"
EndSection
```

In an attempt to fix some serious "screen tearing" I saw when scrolling in Chrome.  Have you had any issues with screen tearing/graphic artifacts?

**Comment by ejmg** [comment]
I have not done anything to my intel drivers because I have not noticed tearing yet. Can you link me a report to it?

Is this unique to chrome? I am using chromium and have also used firefox, but have noticed the tearing on neither. I would assume the issue would come upstream from chromium, but maybe not. Have you tried using chromium?

If this is a real issue, I would love to include it in the tutorial. I just want to verify it and the solution first.

**Comment by mmcdole** [comment]
https://wiki.archlinux.org/index.php/intel_graphics#Xorg_configuration

That link discusses creating the following `/etc/X11/xorg.conf.d/20-intel.conf` file *if* you want to alter any flags for the Intel graphics driver (otherwise no need if you want to rely on the defaults):

```
Section "Device"
  Identifier  "Intel Graphics"
  Driver      "intel"
EndSection
```

It looks like `Option "AccelMethod" "sna"` and `Option "DRI" "3"` are defaults.  However, it mentions X11 might crash if you don't specify the default `sna` accel method for some reason.

I experienced it in both Chrome and Chromium.  Not Firefox as far as I could tell.

I'm curious if you actually have `TearFree` enabled somehow.

Any chance you could do the following?:

` cat /var/log/Xorg.0.log| grep "TearFree"`

I'll try and dig up the source links from others who ran into this with the HD 620 Graphics.  One was a bug on the Chrome/Chromium tracker and another one was a mirrored bug reported on a Ubuntu issue tracker.

**Comment by ejmg** [comment]
> I'm curious if you actually have TearFree enabled somehow.
> 
> Any chance you could do the following?:
> 
> cat /var/log/Xorg.0.log| grep "TearFree"

Nope. I read the wiki section and I'm actually left wondering where the hell xorg sources its default intel settings so as to have a full picture of what is and is not set by default. It's not even in `/usr/share/X11/xorg.conf.d/`and there seems to be no other mentions of it anywhere else. I tried looking in the directories listed in its [man page](ftp://www.x.org/pub/X11R7.7-RC1/doc/man/man5/xorg.conf.5.xhtml) and, for those that existed, I still didn't find anything.

> I'll try and dig up the source links from others who ran into this with the HD 620 Graphics. One was a bug on the Chrome/Chromium tracker and another one was a mirrored bug reported on a Ubuntu issue tracker.

Please do, I would love to track this issue/resolve it within the guide if it a real thing. The only results I found for Intel's HD 620 card from an initial google search/chromium's issue tracker were related to wayland, like [here](https://bugs.chromium.org/p/chromium/issues/detail?id=845795).

> I've created a /etc/X11/ config with the following contents based on responses from other X1C6 owners:

Can I get a link to this? I like keeping tabs on issues that might bite me later, lol.

**All those questions aside:** as it stands, I have no issue adding this recommendation to the guide since other X1C6 users are reporting this issue along with a successful solution. 

However, I think adding a preface along the lines of "Hey, do not do this immediately, ***but if you notice tearing in chrome/ium.....*** would be a good since 1) there's a chance not everyone is effected (me at least???) and, if so, I err towards keeping conf changes at a relative minimum for beginners so tweaks don't inadvertently come around and bite them in the ass somewhere later.

**Comment by ejmg** [comment]
I'm going to go ahead and open an issue for this so it doesn't get lost. IDK how to move what was said above, so I'll just link to here in the issue.

Issue #11

**Pull request merged**
